version: '3.9'
services:
  backend:
    environment:
      STRIPE_SECRET_KEY: 'insert-your-stripe-key'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:delegated
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"